apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkding
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 1m
  timeout: 5m
  path: ./apps/staging/linkding
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: linkding
